use_frameworks!

platform :ios, '9.0'

target 'CustomerFrameworkPods_Example' do
  pod 'CustomerFrameworkPods', :path => '../'

  target 'CustomerFrameworkPods_Tests' do
    inherit! :search_paths

    
  end
end
